wandb_version: 1

'false':
  desc: null
  value: false
out_dir:
  desc: null
  value: out
eval_interval:
  desc: null
  value: 2000
log_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: true
init_from:
  desc: null
  value: gpt2
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: owt
wandb_run_name:
  desc: null
  value: gpt21690275124.7227647
dataset:
  desc: null
  value: javascript_dataset
gradient_accumulation_steps:
  desc: null
  value: 40
batch_size:
  desc: null
  value: 12
block_size:
  desc: null
  value: 1024
n_layer:
  desc: null
  value: 12
n_head:
  desc: null
  value: 12
n_embd:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0006
max_iters:
  desc: null
  value: 600000
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 2000
lr_decay_iters:
  desc: null
  value: 600000
min_lr:
  desc: null
  value: 6.0e-05
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: cpu
dtype:
  desc: null
  value: bfloat16
compile:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690275382.205321
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.5
      6: 4.31.0
      8:
      - 3
      - 5
